export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const SET_USER_DETAILS = 'SET_USER_DETAILS'


export const BOOK_SLOT_REQUEST = 'BOOK_SLOT_REQUEST'
export const BOOK_SLOT_SUCCESS = 'BOOK_SLOT_SUCCESS'
export const BOOK_SLOT_FAILED = 'BOOK_SLOT_FAILED'


export const GET_SHOWS_REQUEST = 'GET_SHOWS_REQUEST'
export const GET_SHOWS_SUCCESS = 'GET_SHOWS_SUCCESS'
export const GET_SHOWS_FAILED = 'GET_SHOWS_FAILED'
export const SHOWS_CLEAN_UP = 'SHOWS_CLEAN_UP'



export const START_TRACK = 'START_TRACK'
export const PLAY_TRACK = 'PLAY_TRACK'
export const PAUSE_TRACK = 'PAUSE_TRACK'
export const PLAY_NEXT_TRACK = 'PLAY_NEXT_TRACK'
export const PLAY_PREV_TRACK = 'PLAY_PREV_TRACK'

export const GET_UPCOMING_SLOT_REQUEST = 'GET_UPCOMING_SLOT_REQUEST'
export const GET_UPCOMING_SLOT_SUCCESS = 'GET_UPCOMING_SLOT_SUCCESS'
export const GET_UPCOMING_SLOT_FAILED = 'GET_UPCOMING_SLOT_FAILED'
export const UPCOMING_SLOT_CLEAN_UP = 'UPCOMING_SLOT_CLEAN_UP'

export const GET_MY_SHOWS_REQUEST = 'GET_MY_SHOWS_REQUEST'
export const GET_MY_SHOWS_SUCCESS = 'GET_MY_SHOWS_SUCCESS'
export const GET_MY_SHOWS_FAILED = 'GET_MY_SHOWS_FAILED'







